GPU:
    GPU_MEMORY_FRACTION: 0.9
    TF_ALLOW_GROWTH: True

MODEL:
    MODEL_NAME: 'vgg'
    WEIGHT_PATH: 'imagenet'

INPUT:
  CONTENT_DIR: './'
  STYLE_DIR: './'
  RESULTS_DIR: './'
  HEIGHT_RESIZE_SIZE: 256

HYPERPARAMETERS:
  STYLE_WEIGHT: 1e-2
  CONTENT_WEIGHT: 1e-32
  OPTIMIZER: 'adam'
  LEARNING_RATE: 0.01
  ITERATION: 800
  SAVE_EVERY_ITER: 10
